const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  navigateTo: (page) => ipcRenderer.send('navigate', page),
  getHomeDirectory: () => ipcRenderer.invoke('get-home-directory'),
  openDirectoryDialog: () => ipcRenderer.invoke('open-directory-dialog'),
  saveProject: (projectData) => ipcRenderer.invoke('save-project', projectData),
  getProjectDetails: (projectId) => ipcRenderer.invoke('get-project-details', projectId),
  getRecentProjects: () => ipcRenderer.invoke('get-recent-projects'),
  getAllProjects: () => ipcRenderer.invoke('getAllProjects'),
  removeProject: (projectId) => ipcRenderer.invoke('remove-project', projectId),
  checkProjectExists: (folderPath) => ipcRenderer.invoke('checkProjectExists', folderPath),
  getFolderInfo: (folderPath) => ipcRenderer.invoke('getFolderInfo', folderPath),
  startProjectCreation: (projectId, projectPath, githubUrl) => ipcRenderer.invoke('start-project-creation', projectId, projectPath, githubUrl),
  reopenProject: (projectId, projectPath, githubUrl, repoFolderName) => ipcRenderer.invoke('reopen-project', projectId, projectPath, githubUrl, repoFolderName),
  openProjectOnlyPreviewAndServer: (projectId, projectPath, githubUrl, repoFolderName) => ipcRenderer.invoke('open-project-only-preview-and-server', projectId, projectPath, githubUrl, repoFolderName),
  cancelProjectCreation: (projectId, projectPath, repoFolderName) => ipcRenderer.invoke('cancel-project-creation', projectId, projectPath, repoFolderName),
  onCommandOutput: (callback) => ipcRenderer.on('command-output', (event, ...args) => callback(...args)),
  onCommandStatus: (callback) => ipcRenderer.on('command-status', (event, ...args) => callback(...args)),
  onDevServerUrl: (callback) => ipcRenderer.on('dev-server-url', (event, ...args) => callback(...args)),
  setBrowserViewBounds: (viewName, bounds) => ipcRenderer.invoke('set-browser-view-bounds', viewName, bounds),
  loadBrowserViewUrl: (viewName, url) => ipcRenderer.invoke('load-browser-view-url', viewName, url),
  setBrowserViewVisibility: (viewName, visible) => ipcRenderer.invoke('set-browser-view-visibility', viewName, visible),
  setAllBrowserViewVisibility: (visible) => ipcRenderer.invoke('set-all-browser-view-visibility', visible),
  getDevServerUrlFromMain: () => ipcRenderer.invoke('get-dev-server-url-from-main'),
  captureBrowserViewPage: (viewName) => ipcRenderer.invoke('capture-browser-view-page', viewName),
  browserViewGoBack: (viewName) => ipcRenderer.invoke('browser-view-go-back', viewName),
  browserViewReload: (viewName) => ipcRenderer.invoke('browser-view-reload', viewName),
  getBrowserViewUrl: (viewName) => ipcRenderer.invoke('get-browser-view-url', viewName),
  clearBrowserCache: () => ipcRenderer.invoke('clear-browser-cache'),
  createNewWindowWithState: (windowState) => ipcRenderer.invoke('create-new-window-with-state', windowState),
  onBrowserViewLoaded: (callback) => ipcRenderer.on('browser-view-loaded', (event, payload) => callback(payload)),
  confirmExitApp: () => ipcRenderer.invoke('confirm-exit-app'),
  onShowExitConfirmation: (callback) => ipcRenderer.on('show-exit-confirmation', callback),
  sendExitConfirmationResponse: (confirmed) => ipcRenderer.send('exit-confirmation-response', confirmed),
  // GitHub authentication functions
  checkGitHubAuth: () => ipcRenderer.invoke('checkGitHubAuth'),
  authenticateWithGitHub: () => ipcRenderer.invoke('authenticateWithGitHub'),
  completeWelcomeSetup: () => ipcRenderer.invoke('completeWelcomeSetup'),
  // Node.js detection and installation functions
  checkNodeInstallation: () => ipcRenderer.invoke('checkNodeInstallation'),
  installNodeDependencies: (options) => ipcRenderer.invoke('installNodeDependencies', options),
  getNodeInstallationProgress: () => ipcRenderer.invoke('getNodeInstallationProgress'),
  // Git branch management functions
  listBranches: (projectId) => ipcRenderer.invoke('git:list-branches', projectId),
  createBranch: (projectId, branchName) => ipcRenderer.invoke('git:create-branch', projectId, branchName),
  checkoutBranch: (projectId, branchName) => ipcRenderer.invoke('git:checkout-branch', projectId, branchName),
  getCurrentBranch: (projectId) => ipcRenderer.invoke('git:get-current-branch', projectId)
});
